### ISSUE TITLE
Error with continuous data: nodes[i] <- possible[best] : replacement has length zero

### ISSUE THREAD

**Issue by willpearse** [traitecoevo/ksi#2] opened 2015-07-06 19:12 UTC
Me again, sorry!

I'm having trouble with continuous data now:

```
tree <- rtree(1000)
tree$node.label <- paste0("nd", seq_len(tree$Nnode))
vals <- setNames(runif(1000), tree$tip.label)
ksi(tree, vals)

depth = 1...Error in nodes[i] <- possible[best] (from <tmp>#44) : replacement has length zero
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

...do you know what I'm doing wrong? Running exactly this code with categorical data (see #1) runs fine, albeit with warnings (which are also triggered in this). Forcing it to run a chi-squared (`test="chisq"`) runs fine, although I guess I wouldn't want that for continuous data.

Thanks for your help. I'm sorry to be pestering you!

**Comment by willpearse** [comment] 2015-07-07 13:59
...after some digging, I can get the function to run, but I don't know whether I've fixed it so just made it not give an error...

Changing line 30 (```  tree <- diversitree:::drop.tip.fixed(tree, to.drop)```) in ```ksi.R``` to:

```
  if(length(to.drop) > 0)
      tree <- drop.tip(tree, to.drop)
```

...seems to do the job for me. For some reason you get a tree with no tip labels but all the nodes retained returned. Things then run for me with no warnings.

Does that help?

**Comment by richfitz** [comment] 2015-07-07 22:30
Possibly/probably worse.  Ape's `drop.tip` is usually broken with respect to node labels, which are key here.  I've contributed two fixes upstream I think but there's no regression tests so ¯\_(ツ)_/¯

Very little time atm, as squaring away projects before moving country.  And I think I explained to you previously that this whole project has left a seriously sour taste for me, though that's obviously not your fault...

**Comment by willpearse** [comment] 2015-07-08 13:20
I forgot you were in transit, sorry!...

My suggestion would be to just crash out if the tree and the data don't match; that way, no one can be angry...

If you're busy, I might fudge around (if I have time!) and do that, write a demo for the help files, and then do a pull request or something. It's the least I can do given how much I've been using this of late!

Thanks Rich!

**Comment by richfitz** [comment] 2015-07-08 21:23
That's OK - I don't think I told you yet!

Be careful - I don't think the problem is the tree dropping.  From where the error turns up it looks like it's an uncaught corner case in the logic.  I'd be inclined to do `options(error=recover)` and see what it's complaining about.   It's also possible that the error is caused by the situation generated by the warnings, so running with `options(warn=2)` may recover the true problem.

**Comment by willpearse** [comment] 2015-07-08 21:27
I'll stop feeling so bad then! :p

I'll keep digging then. I don't get any warnings with this "fix", so maybe that's good or maybe that's bad. More digging...

**Comment by wcornwell** [comment] 2017-07-28 03:44
@willpearse did you ever make progress on this?

**Comment by willpearse** [comment] 2017-07-28 15:54
I can't honestly remember, sorry... If I did anything, it would be here (https://github.com/willpearse/ksi). It doesn't look like I did though :-( I have a vague memory of reading Rich's comments above, panicking, and then calming down a bit and convincing myself it wasn't anything too serious. I was at a meeting, though, which is not necessarily the best place for calm rational thought!...

I would normally offer to help out, but I'm a bit up against it right now. If you do make progress I'd love to know, though :D

**Comment by wcornwell** [comment] 2017-07-30 00:05
Hmmm kinda looks like you did solve it here:

https://github.com/willpearse/ksi/commit/af37a903df2df4f9350cc479fd5f23c814997551

I will do some more testing, but I haven't found anything wrong  with your fix yet.

**Comment by wcornwell** [comment] 2017-08-01 01:51
fixed in https://github.com/traitecoevo/ksi/commit/a7ba857b3c79dba7ef879a361de9af3ea0b3aa6d

**Closed by wcornwell** 2017-08-01 01:51 UTC

**Comment by willpearse** [comment] 2017-08-01 15:23
Cool! Thanks Will
